# launcher name & url
launcher_name=LocalLauncher
launcher_app_name=Local Launcher
launcher_short_name=Local
url_home=https://github.com/simpicutew/ZalithLauncher2-Local

# your OAuth client id
#oauth_client_id=xxx

# your CurseForge API key
#curseforge_api_key=xxx

# default key, please add it yourself.

# launcher version
launcher_version_code=200040
launcher_version_name=2.5.3
